name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  prep:
    name: Prepare the development environment
    environment: development
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.action }}-${{ github.event_name != 'pull_request' || github.run_id }}
      cancel-in-progress: true
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout pushed changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'renv'
          use-public-rspm: true
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::sessioninfo
            local::.
          needs: |
            dev
  lint:
    name: Lint the package
    needs: prep
    environment: development
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.action }}-${{ github.event_name != 'pull_request' || github.run_id }}
      cancel-in-progress: true
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Lint
        run: |
          lintr::lint_package()
        shell: Rscript {0}
  build:
    name: Build the package
    needs: lint
    environment: development
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.action }}-${{ github.event_name != 'pull_request' || github.run_id }}
      cancel-in-progress: true
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Build
        run: |
          devtools::build_readme()
          devtools::check(
            cran = TRUE,
            document = TRUE,
            incoming = FALSE,
            remote = FALSE,
            vignettes = TRUE
          )
        shell: Rscript {0}
