name: docs-on-push

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  build-docs:
    name: 📖 Build the docs
    environment: development
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.action }}-${{ github.event_name != 'pull_request' || github.run_id }}
      cancel-in-progress: true
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: install-system-deps
        name: Install system dependencies
        run: |
          sudo apt-get update;
          sudo apt-get install build-essential coreutils tree
      - id: checkout-pushed
        name: Checkout pushed changes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: set-ref-name
        name: Set REF_NAME environment variable
        run: |
          echo github.ref      = ${{ github.ref }}
          echo github.ref_name = ${{ github.ref_name }}
          echo GITHUB_REF      = "${GITHUB_REF}"
          echo ""
          echo "REF_NAME=${GITHUB_REF#refs/*/}" | tee -a $GITHUB_ENV
      - id: setup-pandoc
        name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - id: setup-r
        name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "renv"
          use-public-rspm: true
      - id: setup-r-dependencies
        name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::sessioninfo
            any::pkgdown
            local::.
          needs: |
            development
      - id: build-readme
        name: Build README.md
        run: |
          devtools::build_readme()
        shell: Rscript {0}
      - id: build-docs
        name: Build docs
        run: |
          devtools::document()
        shell: Rscript {0}
      - id: build-docs-site
        name: Build docs site
        run: |
          pkgdown::build_site_github_pages(
            new_process = FALSE,
            install = FALSE,
            dest_dir = file.path("docs", "dev", Sys.getenv("REF_NAME"))
          )
        shell: Rscript {0}
      - id: report
        name: Report what happened...
        run: |
          set -x
          git status
          git branch -vvv
          env | sort
          tree

