name: docs-on-push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pkgdown:
    environment: dev_environment
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update;
          sudo apt-get install tree
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Determine and set REF_NAME
        run: |
          set -x
          echo "github.ref_name=${{ github.ref_name }}"
          echo "REF_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "renv"
          use-public-rspm: true
      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
      - name: Build pkgdown site
        run: |
          pkgdown::build_site_github_pages(
            new_process = FALSE,
            install = FALSE,
            dest_dir = file.path("docs", Sys.getenv("RELEASE_REF"))
          )
        shell: Rscript {0}
      - name: Report
        run: |
          set -x
          git status
          git branch -vvv
          env | sort
          tree

