name: pkgdown

on:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pkgdown:
    environment: dev_environment
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update;
          sudo apt-get install tree
      - name: Checkout release
        uses: actions/checkout@v4
        with:
          path: release
          fetch-depth: 0
      - name: Determine and set RELEASE_VERSION
        working-directory: ./release
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Setup pandoc
        working-directory: ./release
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup R
        working-directory: ./release
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - name: Setup R dependencies
        working-directory: ./release
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
      - name: Build site
        working-directory: ./release
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE, dest_dir = file.path("docs", Sys.getenv("RELEASE_VERSION")))
        shell: Rscript {0}
      - name: Report
        working-directory: .
        run: |
          env | sort
          tree

